# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ivashmak/Ransac

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ivashmak/Ransac

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ivashmak/Ransac/CMakeFiles /home/ivashmak/Ransac/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ivashmak/Ransac/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ransac

# Build rule for target.
ransac: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ransac
.PHONY : ransac

# fast build rule for target.
ransac/fast:
	$(MAKE) -f CMakeFiles/ransac.dir/build.make CMakeFiles/ransac.dir/build
.PHONY : ransac/fast

Detector/detector.o: Detector/detector.cpp.o

.PHONY : Detector/detector.o

# target to build an object file
Detector/detector.cpp.o:
	$(MAKE) -f CMakeFiles/ransac.dir/build.make CMakeFiles/ransac.dir/Detector/detector.cpp.o
.PHONY : Detector/detector.cpp.o

Detector/detector.i: Detector/detector.cpp.i

.PHONY : Detector/detector.i

# target to preprocess a source file
Detector/detector.cpp.i:
	$(MAKE) -f CMakeFiles/ransac.dir/build.make CMakeFiles/ransac.dir/Detector/detector.cpp.i
.PHONY : Detector/detector.cpp.i

Detector/detector.s: Detector/detector.cpp.s

.PHONY : Detector/detector.s

# target to generate assembly for a file
Detector/detector.cpp.s:
	$(MAKE) -f CMakeFiles/ransac.dir/build.make CMakeFiles/ransac.dir/Detector/detector.cpp.s
.PHONY : Detector/detector.cpp.s

Generator/generator.o: Generator/generator.cpp.o

.PHONY : Generator/generator.o

# target to build an object file
Generator/generator.cpp.o:
	$(MAKE) -f CMakeFiles/ransac.dir/build.make CMakeFiles/ransac.dir/Generator/generator.cpp.o
.PHONY : Generator/generator.cpp.o

Generator/generator.i: Generator/generator.cpp.i

.PHONY : Generator/generator.i

# target to preprocess a source file
Generator/generator.cpp.i:
	$(MAKE) -f CMakeFiles/ransac.dir/build.make CMakeFiles/ransac.dir/Generator/generator.cpp.i
.PHONY : Generator/generator.cpp.i

Generator/generator.s: Generator/generator.cpp.s

.PHONY : Generator/generator.s

# target to generate assembly for a file
Generator/generator.cpp.s:
	$(MAKE) -f CMakeFiles/ransac.dir/build.make CMakeFiles/ransac.dir/Generator/generator.cpp.s
.PHONY : Generator/generator.cpp.s

Ransac/ransac.o: Ransac/ransac.cpp.o

.PHONY : Ransac/ransac.o

# target to build an object file
Ransac/ransac.cpp.o:
	$(MAKE) -f CMakeFiles/ransac.dir/build.make CMakeFiles/ransac.dir/Ransac/ransac.cpp.o
.PHONY : Ransac/ransac.cpp.o

Ransac/ransac.i: Ransac/ransac.cpp.i

.PHONY : Ransac/ransac.i

# target to preprocess a source file
Ransac/ransac.cpp.i:
	$(MAKE) -f CMakeFiles/ransac.dir/build.make CMakeFiles/ransac.dir/Ransac/ransac.cpp.i
.PHONY : Ransac/ransac.cpp.i

Ransac/ransac.s: Ransac/ransac.cpp.s

.PHONY : Ransac/ransac.s

# target to generate assembly for a file
Ransac/ransac.cpp.s:
	$(MAKE) -f CMakeFiles/ransac.dir/build.make CMakeFiles/ransac.dir/Ransac/ransac.cpp.s
.PHONY : Ransac/ransac.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/ransac.dir/build.make CMakeFiles/ransac.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/ransac.dir/build.make CMakeFiles/ransac.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/ransac.dir/build.make CMakeFiles/ransac.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... ransac"
	@echo "... rebuild_cache"
	@echo "... Detector/detector.o"
	@echo "... Detector/detector.i"
	@echo "... Detector/detector.s"
	@echo "... Generator/generator.o"
	@echo "... Generator/generator.i"
	@echo "... Generator/generator.s"
	@echo "... Ransac/ransac.o"
	@echo "... Ransac/ransac.i"
	@echo "... Ransac/ransac.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

